export const SET_GOODS = 'SET_GOODS'
export const ADD_GOODS = 'ADD_GOODS'
export const ADD_GOODS1 = 'ADD_GOODS1'
export const CUT_GOODS = 'CUT_GOODS'
export const CLEAR_GOODS = 'CLEAR_GOODS'
export const ADD_COUNTS = 'ADD_COUNTS'
